def get_academic_department_data():
    return {
        "College of Business":[
            "Information Systems and Business Analytics Department",
            "Accounting",
            "Marketing",
            "Ivy College of Business",
            "Supply Chain Management",
            "Finance",
            "Management and Entrepreneurship",
            "Graduate Business Administration"
        ],
        "College of Agriculture and Life Sciences":[
            "Global Resource Systems",
            "Plant Pathology, Entomology and Microbiology",
            "Agricultural and Biosystems Engineering - A",
            "Natural Resource Ecology and Management",
            "Animal Science",
            "Agronomy",
            "Food Science and Human Nutrition - A",
            "Agricultural Education and Studies",
            "Horticulture",
            "Plant Biology",
            "Genetics, Development and Cell Biology - S",
            "Sustainable Agriculture",
            "Genetics, Development and Cell Biology - A",
            "Learning And Leadership Science"
        ],
        "CELT":[
            "Center For Excellence In Learn & Teach"
        ],
        "College of Design":[
            "Urban Planning and Development",
            "Graphic Design",
            "Landscape Architecture",
            "Architecture",
            "Design Studies",
            "Art and Visual Culture",
            "Interior Design",
            "Design",
            "Game Design"
        ],
        "College of Engineering":[
            "Agricultural and Biosystems Engineering - E",
            "Biomedical Engineering",
            "Cyber Security",
            "Civil, Construction and Environmental Engineering",
            "Mechanical Engineering",
            "Industrial and Manufacturing Systems Engineering",
            "Electrical and Computer Engineering",
            "Aerospace Engineering",
            "College of Engineering",
            "Materials Science and Engineering",
            "Industrial Design",
            "Chemical and Biological Engineering",
            "Software Engineering",
            "Women in Science and Engineering"
        ],
        "College of Health and Human Sciences":[
            "Nursing",
            "Kinesiology and Health",
            "College of Health and Human Sciences",
            "Food Science and Human Nutrition - H",
            "School of Education",
            "Apparel, Events and Hospitality Management",
            "Human Development and Family Studies"
        ],
        "Interdepartmental Programs":[
            "Economics - S",
            "Economics - A",
            "Genetics",
            "Honors Courses",
            "Environmental Science",
            "Environmental Studies",
            "University Studies",
            "Graduate Studies",
            "Earth, Atmosphere, and Climate",
            "Roy J. Carver Department of Biochemistry, Biophysics and Molecular Biology - S",
            "Roy J. Carver Department of Biochemistry, Biophysics and Molecular Biology - A",
            "Ecology, Evolution and Organismal Biology - S",
            "Ecology And Evolutionary Biology",
            "Biology",
            "Toxicology",
            "Molecular Cellular & Developmental Biology",
            "Immunobiology",
            "Human Computer Interaction",
            "Seed Technology And Business",
            "Gerontology"
        ],
        "College of Liberal Arts and Sciences":[
            "Data Science",
            "Womens And Gender Studies",
            "American Indian Studies",
            "International Studies",
            "African & African American Studies",
            "Linguistics",
            "U.S. Latino/A Studies",
            "Artificial Intelligence",
            "Integrated Health Sciences",
            "Bioinformatics & Computational Biology",
            "Neuroscience",
            "Naval Science",
            "College of Liberal Arts and Sciences",
            "History",
            "Chemistry",
            "Music and Theatre",
            "English",
            "Physics and Astronomy",
            "Computer Science",
            "Political Science",
            "World Languages and Cultures",
            "Communication Studies",
            "Sociology and Criminal Justice - S",
            "Mathematics",
            "Statistics",
            "Philosophy and Religious Studies",
            "Psychology",
            "Greenlee School of Journalism and Communication",
            "Leadership Studies",
            "Military Science and Tactics",
            "Bioinformatics & Computional Biology",
            "Bioinformatics and Computational Biology",
            "Sociology and Criminal Justice - A",
            "Air Force Aerospace Studies",
            "Scientific Illustration and Visualization"
        ],
        "Library":[
            "Library"
        ],
        "College of Veterinary Medicine":[
            "Veterinary Clinical Sciences",
            "Veterinary Pathology",
            "Veterinary Microbiology and Preventive Medicine",
            "Veterinary Diagnostic and Production Animal Medicine",
            "Biomedical Sciences"
        ]
        }